### ISSUE TITLE
Documentation : context object specification

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/toki#4]
#### Context

We need additional documentation around the `context` object to help green to us engineers understand what is being offered exactly for the method actions to use.

* `context.request`
  *  what is the exact contract we are offering with decorations on top of the node request object
* `context.reply`
  * what does this action do exactly?
*  How does the actions configuration section map on the `context`

**Comment by lamchakchan** [comment]
@dhinklexo you need to help fill in the blanks for the `context.request` object since you designed that piece.  Documentation should go here in `toki` so that future bridge authors have a contract they can marry to.

**Comment by dhinklexo** [comment]
Are you referring to the bridge? If so that's documented in the bridge api docs: https://github.com/xogroup/toki-hapi-bridge/blob/master/API.md

**Comment by lamchakchan** [comment]
Yes, that's exactly what I'm referring to.  Can you copy that over to the core to as the contract to expect.

**Comment by dhinklexo** [comment]
Will do

**Comment by dhinklexo** [comment]
Resolved
