### ISSUE TITLE
Documentation : config action.type

### ISSUE THREAD

**Issue by lamchakchan** [xogroup/toki#5]
#### Context

* The `action.type` attribute is not clear that this value is what we use to require in `toki-method-*` plugins.  All of the examples have `action.type` names that do not align with our `toki-method-*` plugin signature.  Do we want to consider doing something `webpack` does which is optionally, you can plug in a name that does not prepend with `toki-method` and we will try to prepend the signature if one does not match?  If not, we should be clear in our examples what to expect via a naming convention.

**Comment by cesarhq** [comment]
action.type was freeform, no need to prefix but is that something we need, I can document and code enforce

**Comment by lamchakchan** [comment]
I think free from is fine, But documentation around our `toki` community standards on how we name our plugins.  If you can change the `Examples.md` to also use our naming strategy, it will help.  Up to you if you want to code enforce. :D
